apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-news
  labels:
    app: db-news
spec:
  replicas: 1 #not necessary, default is 1
  template:
    metadata:
      name: db-news
      labels:
        app: db-news
    spec:
      containers:
        - name: db-news-container
          image: aluracursos/mysql-db:1
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: db-configmap
  selector:
    matchLabels:
      app: db-news