apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-motor-deployment
spec:
  replicas: 1 #not necessary, default is 1
  template:
    metadata:
      name: news-motor
      labels:
        app: news-motor
    spec:
      containers:
        - name: news-motor-container
          image: aluracursos/sistema-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: news-motor-configmap
          livenessProbe:
            httpGet:
              path: / #http://localhost:30001/
              port: 80  #containerPort
            periodSeconds: 10 # interval tests
            failureThreshold: 3 # number of fails to trigger restart
            initialDelaySeconds: 20 # wait 20 seconds to start tests
  selector:
    matchLabels:
      app: news-motor