apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-portal-deployment
spec:
  replicas: 3
  template:
    metadata:
      name: news-portal
      labels:
        app: news-portal
    spec:
      containers:
        - name: news-portal-container
          image: aluracursos/portal-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: news-portal-configmap
          livenessProbe:
            httpGet:
              path: / #http://localhost:30000/
              port: 80  #containerPort
            periodSeconds: 10 # interval tests
            failureThreshold: 3 # number of fails to trigger restart
            initialDelaySeconds: 20 # wait 20 seconds to start tests
          readinessProbe:
            httpGet:
              path: / #http://localhost:30000/
              port: 80  #containerPort
            periodSeconds: 10 # interval tests
            failureThreshold: 5 # number of fails to trigger restart
            initialDelaySeconds: 3 # wait 3 seconds to start tests
          resources:
            requests:
              cpu:  10m
  selector:
    matchLabels:
      app: news-portal