apiVersion: v1
kind: pod
metadata:
  name: pod-volume
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /my-volume-in-container
          name: my-volume
    - name: jenkins-container
      image: jenkins:alpine
      volumeMounts:
        - mountPath: /my-volume-in-container
          name: my-volume
  volumes:
    - name: my-volume
      hostPath:
        path: /D/Docker/my-volume
        type: Directory