apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: slow
provisioner: kubernetes.io/gce-pd #google cloud engine platform
parameters:
    type: pd-standard
    fstype: ext4
    replication-type: none